0, room4, -1, 1, -1, -1, -1, 1, starting room
1, room3, 0, 2, 3, 11, 15, 1, safe room
2, room5, 1, 13, -1, -1, -1, 1, kitchen
3, room2, 4, 7, 8, 1, -1, 1, wardrobe room
4, room6, -1, 3, 5, -1, -1, 1, libary
5, room7, 6, -1, -1, 4, 1, -1, master bedroom
6, room11, -1, 5, -1, 12, -1, 1, lab
7, room1,  3, -1, -1, 13, -1, 1, entrance
8, room8, -1, -1, 9, 3, -1, 1, servent room
9, room9, -1, 10, -1, 8, -1, 1, cell room 1
10, room10, 9, -1, -1, -1, -1, 1, cell room 2
11, window, -1, -1, 1, -1, -1, 2, outside safe room
12, table, -1, -1, 6, -1, -1, 3, lab table
13, dindead, 2, 14, 7, -1, -1, 5, dine death 1
14, death, 2, -1, 7, -1, -1, 4, dine death 2
15, safe, -1, 1, -1, -1, -1, 6, safe
